<template>
    <div id="privacy">
      <h1>
        <strong>Privacy Policy- WorkBoost</strong>
      </h1>
      <p>&nbsp;</p>
      <p>
        Your privacy is important to us. It is WorkBoost's policy to respect your privacy regarding any information we may collect from you across our Website,&nbsp;
        <a
          href="https://workboost.io/"
        >https://workboost.io</a>, and other sites we own and operate.
      </p>
      <p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we&rsquo;re collecting it and how it will be used.</p>
      <p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we&rsquo;ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or modification.</p>
      <p>We don&rsquo;t share any personally identifying information publicly or with third-parties, except when required to by law.</p>
      <p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
      <p>You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.</p>
      <p>The Website utilizes cookies to enhance online user experience. Cookies are small text files that are generated by the Website that you are viewing, allowing the Website to store information as you navigate web pages. These text files contain session data that can be useful to improve your browsing experience.</p>
      <p>All of the cookies used by the Website are safe for your computer or mobile device and they only store information that is used by the browser. These cookies cannot execute code and cannot be used to access content on your computer. Many of these cookies are necessary to ensure the proper functioning of the Website. They do not contain malware or viruses. Other cookies improve user experience by storing site preferences, language preferences, as well as information about previously viewed content. This information is stored by cookies and used to enhance user experience, such as identifying and resolving errors and navigation problems. We also use cookies to be able to target advertising to the correct User and the correct time, to make it as relevant as possible for our Users.</p>
      <p>To enhance our understanding of your interaction with our Sites, we may use cookies to collect data for statistical purposes, including (but not limited to): date of first visit, number of visits, date of last visit, URL, domain, browser, and screen resolution.</p>
      <p>Cookies, by themselves, do not tell us any personally identifiable information other than your IP address.</p>
      <p>You may voluntarily de-activate and/or eliminate cookies by following your Internet browser's instructions. However WorkBoost reserves the right to not provide you with the Application if you do, because some base functionality and the security of the Application depend on the use of cookies.</p>
      <p>We may partner with third-party ad networks to either display advertising on our Website or to manage our advertising on other websites. Our ad network partners use cookies and Web beacons to collect non-personally identifiable information about your activities on this and other websites to show you targeted advertising based on your interests. We may partner with third-party data providers to match IP addresses with company names and contact names. Our data partners may use cookies and Web beacons for the purpose of matching IP addresses.</p>
      <p>
        Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us at
        <a
          href="mailto:hello@workboost.io"
        >hello@workboost.io</a>.
      </p>
      <p>&nbsp;</p>
      <p>
        <em>This policy is effective as of 24 November 2018.</em>
      </p>
      </div>
</template>
<style lang="scss">
#privacy {
  background: white;
  height: 40%;
  padding-top: 80px;
}
</style>
